# Generated by Django 3.0.6 on 2020-05-10 17:53

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=64, null=True, verbose_name='昵称')),
                ('gender', models.CharField(choices=[('0', '女'), ('1', '男')], max_length=10, verbose_name='性别')),
                ('mid', models.CharField(max_length=128, verbose_name='账号')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.EmailField(blank=True, max_length=128, verbose_name='邮箱地址')),
                ('phone', models.CharField(max_length=11, null=True, unique=True, verbose_name='电话')),
                ('image', models.ImageField(default='user/default1.jpg', max_length=256, upload_to='user/%Y/%m')),
            ],
            options={
                'verbose_name_plural': '管理员用户密码表',
                'db_table': '管理员用户密码表',
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuname', models.CharField(max_length=64, null=True, verbose_name='昵称')),
                ('gender', models.CharField(choices=[('0', '女'), ('1', '男')], max_length=10, null=True, verbose_name='性别')),
                ('stuid', models.CharField(max_length=128, verbose_name='登录账号')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.EmailField(blank=True, max_length=128, verbose_name='邮箱地址')),
                ('phone', models.CharField(max_length=11, null=True, unique=True, verbose_name='电话')),
                ('image', models.ImageField(default='user/default1.jpg', max_length=256, upload_to='user/%Y/%m')),
            ],
            options={
                'verbose_name_plural': '学生用户密码表',
                'db_table': '学生用户密码表',
            },
        ),
        migrations.CreateModel(
            name='TbApartment',
            fields=[
                ('room_no', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='房间号')),
                ('bed_no', models.CharField(max_length=10, unique=True, verbose_name='床号')),
                ('kz_number', models.IntegerField(verbose_name='可住人数')),
                ('xz_number', models.IntegerField(verbose_name='现住人数')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '公寓号信息表',
                'db_table': '公寓号信息表',
            },
        ),
        migrations.CreateModel(
            name='TbFloor',
            fields=[
                ('lou_no', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='楼号')),
                ('rooms', models.IntegerField(verbose_name='房间数')),
            ],
            options={
                'verbose_name_plural': '公寓楼表',
                'db_table': '公寓楼表',
            },
        ),
        migrations.CreateModel(
            name='TbManage',
            fields=[
                ('m_no', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='管理员编号')),
                ('m_name', models.CharField(max_length=20, verbose_name='管理员姓名')),
                ('m_sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=10, verbose_name='性别')),
                ('m_tele', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='电话')),
                ('image', models.ImageField(default='user/default1.jpg', max_length=256, upload_to='user/%Y%d')),
            ],
            options={
                'verbose_name_plural': '管理员信息表',
                'db_table': '管理员信息表',
            },
        ),
        migrations.CreateModel(
            name='TbSgy',
            fields=[
                ('sgy_no', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='宿管员号')),
                ('sgy_name', models.CharField(max_length=10, verbose_name='宿管员姓名')),
                ('sgy_sex', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], default='男', max_length=10, null=True, verbose_name='性别')),
                ('sgy_age', models.SmallIntegerField(blank=True, null=True, verbose_name='年龄')),
                ('sgy_tele', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='电话')),
                ('sgy_rz', models.CharField(blank=True, max_length=10, null=True, verbose_name='职位')),
                ('image', models.ImageField(default='user/default1.jpg', max_length=256, null=True, upload_to='user/%Y%m')),
                ('lou_no', models.ForeignKey(blank=True, db_column='lou_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='ApartmentSystem.TbFloor', verbose_name='楼号')),
            ],
            options={
                'verbose_name_plural': '宿管员信息表',
                'db_table': '宿管员信息表',
            },
        ),
        migrations.CreateModel(
            name='TbStudent',
            fields=[
                ('s_no', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学号')),
                ('s_name', models.CharField(max_length=10, verbose_name='姓名')),
                ('s_sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=10, verbose_name='性别')),
                ('s_age', models.IntegerField(verbose_name='年龄')),
                ('s_tele', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='电话')),
                ('s_college', models.CharField(max_length=20, verbose_name='所属学院')),
                ('image', models.ImageField(default='user/default1.jpg', max_length=256, upload_to='user/%Y/%m')),
                ('m_no', models.ForeignKey(db_column='m_no', on_delete=django.db.models.deletion.DO_NOTHING, to='ApartmentSystem.TbManage', verbose_name='管理员编号')),
            ],
            options={
                'verbose_name_plural': '学生信息表',
                'db_table': '学生信息表',
            },
        ),
        migrations.CreateModel(
            name='TbVisit',
            fields=[
                ('visitor_name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='来访者姓名')),
                ('visitor_tele', models.CharField(max_length=20, unique=True, verbose_name='来访者电话')),
                ('visit_time', models.CharField(max_length=20, verbose_name='来访时间')),
                ('end_time', models.CharField(max_length=20, verbose_name='结束时间')),
                ('visit_sy', models.CharField(blank=True, max_length=30, null=True, verbose_name='事由')),
                ('hoster_name', models.CharField(max_length=20, verbose_name='被访者')),
                ('hoster_no', models.ForeignKey(db_column='hoster_no', on_delete=django.db.models.deletion.CASCADE, to='ApartmentSystem.TbStudent', verbose_name='被访者学号')),
                ('zbr', models.ForeignKey(blank=True, db_column='zbr', null=True, on_delete=django.db.models.deletion.CASCADE, to='ApartmentSystem.TbSgy', verbose_name='值班人')),
            ],
            options={
                'verbose_name_plural': '来访者登记表',
                'db_table': '来访者登记表',
            },
        ),
        migrations.CreateModel(
            name='TbSthFix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200, verbose_name='报修内容')),
                ('report_time', models.CharField(max_length=20, verbose_name='报修时间')),
                ('reporter', models.CharField(blank=True, max_length=20, null=True, verbose_name='报修人')),
                ('fix_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='维修时间')),
                ('fixer', models.CharField(blank=True, max_length=20, null=True, verbose_name='维修人')),
                ('state', models.TextField(blank=True, max_length=256, null=True, verbose_name='维修状态')),
                ('image', models.ImageField(default='image/default.jpg', max_length=256, null=True, upload_to='image/content/%Y/%m%d')),
                ('lou_no', models.ForeignKey(db_column='lou_no', on_delete=django.db.models.deletion.CASCADE, to='ApartmentSystem.TbFloor', verbose_name='楼号')),
                ('room_no', models.ForeignKey(db_column='room_no', on_delete=django.db.models.deletion.CASCADE, to='ApartmentSystem.TbApartment', verbose_name='房间号')),
            ],
            options={
                'verbose_name_plural': '报修管理信息表',
                'db_table': '报修管理信息表',
            },
        ),
        migrations.CreateModel(
            name='TbSsws',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.IntegerField(blank=True, null=True, verbose_name='得分')),
                ('descores', models.CharField(blank=True, max_length=50, null=True, verbose_name='扣分原因')),
                ('comment_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='检查时间')),
                ('comment_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='评测人')),
                ('image', models.ImageField(max_length=256, null=True, upload_to='image/content/%Y/%m/%d')),
                ('lou_no', models.ForeignKey(blank=True, db_column='lou_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='ApartmentSystem.TbFloor', verbose_name='楼号')),
                ('room_no', models.ForeignKey(blank=True, db_column='room_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='ApartmentSystem.TbApartment', verbose_name='房间号')),
            ],
            options={
                'verbose_name_plural': '宿舍卫生信息表',
                'db_table': '宿舍卫生信息表',
            },
        ),
        migrations.CreateModel(
            name='TbSdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_field', models.CharField(blank=True, db_column='month_', max_length=4, null=True, verbose_name='月份')),
                ('elect', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='用电量')),
                ('electric', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='电费')),
                ('water', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='水量')),
                ('waterc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='水费')),
                ('lou_no', models.ForeignKey(blank=True, db_column='lou_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='ApartmentSystem.TbFloor', verbose_name='楼号')),
                ('room_no', models.ForeignKey(blank=True, db_column='room_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='ApartmentSystem.TbApartment', verbose_name='房间号')),
            ],
            options={
                'verbose_name_plural': '水电表',
                'db_table': '水电表',
            },
        ),
        migrations.CreateModel(
            name='TbLx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='床位号')),
                ('l_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='离开时间')),
                ('l_reason', models.TextField(blank=True, max_length=20, null=True, verbose_name='离开原因')),
                ('room_no', models.ForeignKey(blank=True, db_column='room_no', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ApartmentSystem.TbApartment', verbose_name='房间号')),
                ('s_no', models.ForeignKey(blank=True, db_column='s_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='ApartmentSystem.TbStudent', verbose_name='学号')),
            ],
            options={
                'verbose_name_plural': '离校信息表',
                'db_table': '离校信息表',
            },
        ),
        migrations.CreateModel(
            name='TbIllegal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stamp_time', models.CharField(max_length=20, verbose_name='违规时间')),
                ('wreason', models.TextField(max_length=500, verbose_name='违规事件')),
                ('lou_no', models.ForeignKey(blank=True, db_column='lou_no', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ApartmentSystem.TbFloor', verbose_name='楼号')),
                ('room_no', models.ForeignKey(blank=True, db_column='room_no', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ApartmentSystem.TbApartment', verbose_name='房间号')),
                ('s_no', models.ForeignKey(blank=True, db_column='s_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='ApartmentSystem.TbStudent', verbose_name='学号')),
            ],
            options={
                'verbose_name_plural': '违规记录表',
                'db_table': '违规记录表',
            },
        ),
        migrations.AddField(
            model_name='tbfloor',
            name='m_no',
            field=models.ForeignKey(db_column='m_no', on_delete=django.db.models.deletion.DO_NOTHING, to='ApartmentSystem.TbManage', verbose_name='管理员编号'),
        ),
        migrations.AddField(
            model_name='tbapartment',
            name='lou_no',
            field=models.ForeignKey(db_column='lou_no', on_delete=django.db.models.deletion.CASCADE, to='ApartmentSystem.TbFloor', verbose_name='楼号'),
        ),
        migrations.AddField(
            model_name='tbapartment',
            name='m_no',
            field=models.ForeignKey(db_column='m_no', on_delete=django.db.models.deletion.DO_NOTHING, to='ApartmentSystem.TbManage', verbose_name='管理员编号'),
        ),
        migrations.AddField(
            model_name='tbapartment',
            name='s_no',
            field=models.ForeignKey(db_column='s_no', on_delete=django.db.models.deletion.DO_NOTHING, to='ApartmentSystem.TbStudent', verbose_name='学号'),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('picture', models.CharField(max_length=50, verbose_name='标签')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='内容')),
                ('image', models.ImageField(default='user/default1.jpg', max_length=256, upload_to='user/%Y/%m', verbose_name='文章图片')),
                ('publish_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('clicked', models.IntegerField(default=0, verbose_name='点击量')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='ApartmentSystem.TbIllegal', verbose_name='类型')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='ApartmentSystem.TbStudent', verbose_name='用户')),
            ],
            options={
                'verbose_name': '文章内容',
                'verbose_name_plural': '文章内容',
                'db_table': 'content',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='评论内容')),
                ('publish_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间')),
                ('state', models.BooleanField(default=True, verbose_name='审核状态')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApartmentSystem.Content', verbose_name='新闻')),
                ('restore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApartmentSystem.Comment', verbose_name='回复对象')),
                ('restore_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restore', to='ApartmentSystem.TbStudent', verbose_name='回复的用户')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApartmentSystem.TbStudent', verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论表',
                'verbose_name_plural': '评论表',
                'db_table': 'comment',
            },
        ),
    ]
