# Generated by Django 3.0.6 on 2020-05-20 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ApartmentSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbsgy',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=256, verbose_name='密码'),
            preserve_default=False,
        ),
    ]
